### ISSUE TITLE
Fail to install on alpine based docker image

### ISSUE THREAD

**Issue by jonathan-s** [ijl/orjson#104]
I get the following error. It's installed with poetry. I tried a regular pip install, which seemed to work. 
```
Command ['/root/.cache/pypoetry/virtualenvs/foxflash-9TtSrW0h-py3.6/bin/pip', 'install', '--no-deps', 'orjson==3.1.0'] errored with the following return code 1, and output:
Collecting orjson==3.1.0
  Using cached https://files.pythonhosted.org/packages/fb/09/b96e12259bfdc9fb70e9dcf8e05fd6297a6a539582c0c835f41c3c3c3a7f/orjson-3.1.0.tar.gz
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-5m15uc_e/orjson/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5m15uc_e/orjson/
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ijl** [comment]
If it installed build dependencies, did it correctly read `pyproject.toml` and then error with an unnecessary assumption that `setup.py` exists? I suggest raising an issue with the Poetry project for it not handling this case when pip does. If including a no-op `setup.py` papers over this, that would be fine. I looked quickly and don't see a way to test installing from a local sdist with poetry.
