### ISSUE TITLE
Raspberry Pi 4 - Cannot install orjson

### ISSUE THREAD

**Issue by QuentinDanjou** [ijl/orjson#130]
I am trying to install orjson with Python 3.8, so far I have installed wheel, rust nightly and maturin "successfully". On orjson install when it comes to maturin it fails and I can't figure out a solution.

```
$ pip3 install orjson
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting orjson
  Using cached orjson-3.4.0.tar.gz (655 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: orjson
  Building wheel for orjson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpx8a20kfc
       cwd: /tmp/pip-install-34awlfxz/orjson
  Complete output (7 lines):
  💥 maturin failed
    Caused by: The given list of python interpreters is invalid
    Caused by: python is not a valid python interpreter
    Caused by: Failed to get information from the python interpreter at python
    Caused by: Only python >= 3.5 is supported, while you're using python 2.7
  Running `maturin pep517 build-wheel -i python --manylinux=off --strip=on`
  Error: Command '['maturin', 'pep517', 'build-wheel', '-i', 'python', '--manylinux=off', '--strip=on']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for orjson
Failed to build orjson
ERROR: Could not build wheels for orjson which use PEP 517 and cannot be installed directly
```
Both my `pip` and `pip3` are using Python 3.8
I did `$ alias python=python3` without success.

Note: I am building it on a Raspberry Pi 4, so it's an ARM architecture.

```
$ pip -V
pip 20.2.3 from /home/pi/.local/lib/python3.8/site-packages/pip (python 3.8)
$ python --version
Python 3.8.6
$ maturin -V
maturin 0.8.3
$ wheel version
wheel 0.35.1
$ rustc -V
rustc 1.48.0-nightly (7f7a1cbfd 2020-09-27)
```

________________
_I have to admit I wasn't ready to spend that much time on this package as I ran it so smoothly on my x64 computer 😅 (I didn't expect it to have so many requirements! At least orjson is fast!)_

**Comment by QuentinDanjou** [comment]
Hey!

I have some news. It seems that `maturin` is using `sys.executable` so I was able to go around by a simple `sudo update-alternatives --config python`.
I now have a new error a bit further in the build:

```
...
Compiling serde_json v1.0.53 (/tmp/pip-install-rcxt3h2r/orjson/json)
  error: could not compile `packed_simd`

  To learn more, run the command again with --verbose.
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C link-arg=-s`
  Running `maturin pep517 build-wheel -i python --manylinux=off --strip=on`
  Error: Command '['maturin', 'pep517', 'build-wheel', '-i', 'python', '--manylinux=off', '--strip=on']' returned non-zero exit status 1.
  Building wheel for orjson (PEP 517) ... error
  ERROR: Failed building wheel for orjson
Failed to build orjson
ERROR: Could not build wheels for orjson which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 364, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for orjson which use PEP 517 and cannot be installed directly
Removed build tracker: '/tmp/pip-req-tracker-g9mvstpw'
```

**Comment by ijl** [comment]
You should build with `nightly-2020-09-14`, but if you are not using the manylinux2014 aarch64 wheel on PyPI it looks like you may be using a 32-bit environment, and that's unsupported and may not work.

**Comment by QuentinDanjou** [comment]
Yes I am on a 32-bit environment (armv7l), I just realized orjson doesn't support it. Any plan/trial so far to bring the support to 32bit?

**Comment by ijl** [comment]
You're welcome to submit patches but it will not be supported because of CI availability.
