### ISSUE TITLE
Missing build dependency toml in pyproject.toml

### ISSUE THREAD

**Issue by mzpqnxow** [ijl/orjson#223]
Hello-

First, thank you for this project, and thank you first your assistance a while back (probably a year now?) in helping to do what was necessary to get it to build on linux/ppc64le

The issue I'm having when building this as of today (it's been a while since I needed to build because of my wheelhouse/cache)

```
File "/tmp/pip-build-env-5l0qq30z/overlay/lib/python3.8/site-packages/maturin/__init__.py", line 19, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

This is an easy fix:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index ae4a113..a3afa92 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -4,7 +4,7 @@ repository = "https://github.com/ijl/orjson"
 
 [build-system]
 build-backend = "maturin"
-requires = ["maturin>=0.11.4,<0.12"]
+requires = ["maturin>=0.11.4,<0.12", "toml"]
 
 [tool.maturin]
 sdist-include = ["Cargo.lock"]
```

I will send a PR in a few moments, if you agree that it's the correct way to fix it, it would be great if you could merge it and push it out at some point to the PyPi package. Maybe the toml version should be locked. I used `toml==0.10.2`

Thanks again

**Comment by mzpqnxow** [comment]
I should note, the output above with the error is from `pip install`, on linux/ppc64le, Python3.8

**Comment by konstin** [comment]
I'm surprised that this happens, given that maturin both [in 0.11.5](https://github.com/PyO3/maturin/blob/0220fd94fd51be3eaf747e0539bd93177337e553/pyproject.toml#L3) and in [main](https://github.com/PyO3/maturin/blob/6fc4f9f4be533a81de375973b4f5374ef2da1060/pyproject.toml#L3) requires toml, so by the rules of PEP 517/PEP 518 pip must provide an environment with toml installed.

What version of pip are you using?

**Comment by mzpqnxow** [comment]
> I'm surprised that this happens, given that maturin both [in 0.11.5](https://github.com/PyO3/maturin/blob/0220fd94fd51be3eaf747e0539bd93177337e553/pyproject.toml#L3) and in [main](https://github.com/PyO3/maturin/blob/6fc4f9f4be533a81de375973b4f5374ef2da1060/pyproject.toml#L3) requires toml, so by the rules of PEP 517/PEP 518 pip must provide an environment with toml installed.

I wonder if this is because maturin requires it as a *build* time dependency, and (if I understand it correctly) that makes it available only during the build of maturin- not necessarily during the build of anything that *depends* upon maturin? That's not a rhetorical question by the way, I'm far from an expert on PEP 517/PEP 518 and have still not used pyproject.toml in any of my projects. It was my understanding that this was the way it worked, with special care taken to isolation of each package at build-time, to preempt cases where `package_x` requires `buildtool1<2` and `package_y` requires `buildtool1>1` (dumb contrived example)

The version of pip is 21.1.2, so it's nothing *that* old- I can try with pip 21.3.1, which I believe is the latest

Note that I'm running this in a virtualenv with the following in `pip.ini`:

```
[global]
respect-virtualenv = true
[install]
no-dependencies = no
```

Also, here is the full stacktrace from the following two commands (I tried both just to ensure I wasn't doing something silly):

1. `pip install 'git+https://github.com/ijl/orjson@master#egg=orjson'`
2. `git clone https://github.com/ijl/orjson && pip install orjson/`

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 318, in run
    requirement_set = resolver.resolve(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    r = self.factory.make_requirement_from_install_req(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 429, in make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 200, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    super().__init__(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 34, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 88, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 168, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 275, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/user/bootstrap.newdev/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/opt/Python3.9.5/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/pip-build-env-8zmev_pq/overlay/lib/python3.9/site-packages/maturin/__init__.py", line 19, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the '/home/user/bootstrap.newdev/venv/bin/python -m pip install --upgrade pip' command.
(venv) 
15:10:16 › pip list | grep toml
toml               0.10.2
WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the '/home/user/bootstrap.newdev/venv/bin/python -m pip install --upgrade pip' command.
(venv) 
```

**Comment by mzpqnxow** [comment]
Intereting, so this may shed some light on things (or maybe not) ...

```
pip install --no-build-isolation 'git+https://github.com/ijl/orjson@master#egg=orjson'
```

... as expected this fails because it can't find `maturin`

However, if I install `maturin` manually first, and then use:

```
pip install --no-build-isolation 'git+https://github.com/ijl/orjson@master#egg=orjson'
```

... the build is successful. Seems there is *something* to do with build isolation here, though it's probably not as simple as I imagine(d) it to be

**Comment by mzpqnxow** [comment]
Another observation, the failure occurs *before* `maturin` is pulled down as a dependency. So whatever `maturin` may ask for hasn't even been looked at yet (that stack trace is the FULL output from `pip`- I don't see `maturin` in there anywhere)

**Comment by ijl** [comment]
CI exercises the latest pip on amd64 and aarch64 without showing this so I wonder if it's a regression in pip on some edge case around ppc64le.

I'm reluctant to add the dependency because orjson is packaged in a few distros where build systems won't just pull stuff from PyPI and I don't want to cost them time.

**Comment by mzpqnxow** [comment]
> 
> CI exercises the latest pip on amd64 and aarch64 without showing this so I wonder if it's a regression in pip on some edge case around ppc64le.
> 

Interesting, yeah that's certainly possible

> I'm reluctant to add the dependency because orjson is packaged in a few distros where build systems won't just pull stuff from PyPI and I don't want to cost them time.

Fair enough- totally fine with me if we close this for now- until then I'm pointing stuff at my branch- not a big deal at all

I'll leave it up to you, if you'd like to close this, please do

Thanks!

**Comment by ijl** [comment]
Ok.
