### ISSUE TITLE
Can not load exception class: {}.{}json.JSONDecodeError

### ISSUE THREAD

**Issue by leobuskin** [ijl/orjson#24]
I have some interesting situation with `orjson==2.0.6` in my project. I wasn't able to reproduce this issue outside of the project, it means there's probably some strange conflict with existing dependencies or environment. Clean module outside of the project but in the same venv and same imports works absolutely fine.

Any idea what it can be?

*Python*: 3.6.3

PyCharm output:
```
thread '<unnamed>' panicked at 'Can not load exception class: {}.{}json.JSONDecodeError: PyErr { type: Py(0x9d0c40, PhantomData) }', src/libcore/result.rs:999:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: PyInit_orjson
  10: _PyImport_LoadDynamicModuleWithSpec
  11: <unknown>
  12: PyCFunction_Call
  13: _PyEval_EvalFrameDefault
  14: <unknown>
  15: <unknown>
  16: _PyEval_EvalFrameDefault
  17: <unknown>
  18: <unknown>
  19: _PyEval_EvalFrameDefault
  20: <unknown>
  21: <unknown>
  22: _PyEval_EvalFrameDefault
  23: <unknown>
  24: <unknown>
  25: _PyEval_EvalFrameDefault
  26: <unknown>
  27: <unknown>
  28: _PyEval_EvalFrameDefault
  29: <unknown>
  30: _PyFunction_FastCallDict
  31: _PyObject_FastCallDict
  32: _PyObject_CallMethodIdObjArgs
  33: PyImport_ImportModuleLevelObject
  34: _PyEval_EvalFrameDefault
  35: <unknown>
  36: PyEval_EvalCode
  37: <unknown>
  38: PyCFunction_Call
  39: _PyEval_EvalFrameDefault
  40: <unknown>
  41: <unknown>
  42: _PyEval_EvalFrameDefault
  43: <unknown>
  44: <unknown>
  45: _PyEval_EvalFrameDefault
  46: <unknown>
  47: <unknown>
  48: _PyEval_EvalFrameDefault
  49: <unknown>
  50: <unknown>
  51: _PyEval_EvalFrameDefault
  52: <unknown>
  53: _PyFunction_FastCallDict
  54: _PyObject_FastCallDict
  55: _PyObject_CallMethodIdObjArgs
  56: PyImport_ImportModuleLevelObject
  57: _PyEval_EvalFrameDefault
  58: <unknown>
  59: PyEval_EvalCode
  60: <unknown>
  61: PyCFunction_Call
  62: _PyEval_EvalFrameDefault
  63: <unknown>
  64: <unknown>
  65: _PyEval_EvalFrameDefault
  66: <unknown>
  67: <unknown>
  68: _PyEval_EvalFrameDefault
  69: <unknown>
  70: <unknown>
  71: _PyEval_EvalFrameDefault
  72: <unknown>
  73: <unknown>
  74: _PyEval_EvalFrameDefault
  75: <unknown>
  76: _PyFunction_FastCallDict
  77: _PyObject_FastCallDict
  78: _PyObject_CallMethodIdObjArgs
  79: PyImport_ImportModuleLevelObject
  80: _PyEval_EvalFrameDefault
  81: <unknown>
  82: PyEval_EvalCode
  83: <unknown>
  84: PyCFunction_Call
  85: _PyEval_EvalFrameDefault
  86: <unknown>
  87: <unknown>
  88: _PyEval_EvalFrameDefault
  89: <unknown>
  90: <unknown>
  91: _PyEval_EvalFrameDefault
  92: <unknown>
  93: <unknown>
  94: _PyEval_EvalFrameDefault
  95: <unknown>
  96: <unknown>
  97: _PyEval_EvalFrameDefault
  98: <unknown>
  99: _PyFunction_FastCallDict
```

**Comment by leobuskin** [comment]
Ok, that's funny, seems like I figured out the issue, now it's reproducible, but I'm not sure if it should be fixed or not.

1. Create `json.py` file with next content:
```
import orjson
print(orjson.dumps({'1': 1}))
```
2. Run `python json.py` (w/o debugger it hangs, with debugger it raises `thread '<unnamed>' panicked at 'Can not load exception class: {}.{}json.JSONDecodeError: PyErr { type: Py(0x9d0c40, PhantomData) }', src/libcore/result.rs:999:5` and shows the same stack trace.

**Comment by ijl** [comment]
Ah, yeah, I think there's nothing to be done by this project about Python path issues like that. I'm glad you figured it out.
