### ISSUE TITLE
Infinite Loop if `default=` also returns non-serializable

### ISSUE THREAD

**Issue by mattsta** [ijl/orjson#245]
We can trigger an infinite memory consuming loop if the default handler doesn't return a good value...

Complete example:

```python

import orjson
import base64

# Infinite loop of sadness
orjson.dumps(dict(hello=b"there we are"), default=lambda x: base64.b64encode(x))

# Non-infinite loop version
orjson.dumps(dict(hello=b"there we are"), default=lambda x: base64.b64encode(x).decode())
```

Not sure if the `default=` handler should have a built-in recursion check to prevent badness?

**Comment by ijl** [comment]
```python
>>> import orjson
>>> import base64

>>> data = {"key": b"value"}

>>> orjson.dumps(data, default=lambda x: x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: default serializer exceeds recursion limit
```

This trivial example shows the issue as stated isn't correct and I'm surprised you did not think it necessary to check that. The documentation also states that this check exists.

```python
>>> def default(obj):
...     return base64.b64encode(obj)
...

>>> orjson.dumps(data, default=default)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: bytes
```

This was increasing memory usage but still shows the intended `TypeError` when aborted.

```python
>>> idx = 0
>>> def default(obj):
...     idx += 1
...     return base64.b64encode(obj)
...
>>> orjson.dumps(data, default=default)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: bytes
```

This returns to the VM before calling `base64` and does not show the issue.

When it is running uninterrupted, the time is spent in `binascii`.

```
+  100.00%     0.00%  python3  [unknown]                                 [.] 0x00007effeddd4220
+   31.66%     0.00%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x00007effed0551bc
+   25.17%     0.00%  python3  [unknown]                                 [.] 0x00000001361be472
+   19.45%     0.00%  python3  [unknown]                                 [.] 0x00000000e894eb52
+   14.48%     0.00%  python3  [unknown]                                 [.] 0x00000000ae6fb07a
+   13.70%     0.01%  python3  [unknown]                                 [.] 0xffffffff83a00ace
+   12.96%     0.01%  python3  [unknown]                                 [.] 0xffffffff839a7874
+   12.38%     0.01%  python3  [unknown]                                 [.] 0xffffffff82e84342
+   11.68%     0.01%  python3  [unknown]                                 [.] 0xffffffff8304abc2
+   11.49%    11.49%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x00000000000031bc
+   11.16%     0.00%  python3  [unknown]                                 [.] 0xffffffff8304b55c
+   11.00%     0.00%  python3  [unknown]                                 [.] 0x0000000082d3c45a
+    8.58%     8.58%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x000000000000316e
+    8.58%     0.00%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x00007effed05516e
+    8.41%     0.00%  python3  [unknown]                                 [.] 0xffffffff8304faef
+    8.23%     0.00%  python3  [unknown]                                 [.] 0xffffffff8306a474
+    8.14%     8.14%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x0000000000003127
+    8.14%     0.00%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x00007effed055127
+    8.13%     0.00%  python3  [unknown]                                 [.] 0x00000000621ed342
+    7.63%     7.63%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x0000000000003203
+    7.63%     0.00%  python3  binascii.cpython-310-x86_64-linux-gnu.so  [.] 0x00007effed055203
...
```

I don't know, it looks like you want to file an issue against CPython. There is nothing different this library can do.

**Comment by mattsta** [comment]
womp womp

your example is flawed because `idx` isn't referenced as `global idx` in your `default()` so your `TypeError` is because the `idx` reference exception, not because of the blah blah you get it.

infinite recursion proof:

```python
In [4]: def default(x):
   ...:     print("trying...")
   ...:     return base64.b64encode(x)

In [5]: orjson.dumps(dict(hello=b"there we are"), default=default)
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
trying...
^C^C
KeyboardInterrupt
```
