### ISSUE TITLE
A subclass of str cannot be serialized

### ISSUE THREAD

**Issue by j5255089** [ijl/orjson#251]
[type(i) for i in a]
Out[109]: 
[sqlalchemy.sql.elements.quoted_name,
 sqlalchemy.sql.elements.quoted_name,
 sqlalchemy.sql.elements.quoted_name,
 sqlalchemy.sql.elements.quoted_name,
 sqlalchemy.sql.elements.quoted_name,
 sqlalchemy.sql.elements.quoted_name]
a
Out[110]: 
{'id': 339,
 'manualId': 'n_lje',
 'name': '年度_累积额',
 'description': '年度累计额',
 'envs': '',
 'rule_type': ''}
ujson.dumps(a)
Out[111]: '{"id":339,"manualId":"n_lje","name":"\\u5e74\\u5ea6_\\u7d2f\\u79ef\\u989d","description":"\\u5e74\\u5ea6\\u7d2f\\u8ba1\\u989d","envs":"","rule_type":""}'
orjson.dumps(a)
Traceback (most recent call last):
  File "C:\Program Files\Python38\Lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-112-19872c31cca5>", line 1, in <module>
    orjson.dumps(a)
TypeError: Dict key must be str
json.dumps(a)
Out[113]: '{"id": 339, "manualId": "n_lje", "name": "\\u5e74\\u5ea6_\\u7d2f\\u79ef\\u989d", "description": "\\u5e74\\u5ea6\\u7d2f\\u8ba1\\u989d", "envs": "", "rule_type": ""}'
issubclass(quoted_name, str)
Out[114]: True

**Comment by edgarrmondragon** [comment]
Bump, facing a similar issue with `sqlalchemy.sql.elements.quoted_name`. I don't know one iota of Rust, but I wonder if this check here:

https://github.com/ijl/orjson/blob/acaecd2409231106307719f7288e51ebdbb9b24d/src/serialize/dict.rs#L73

could be made so it checks if the key is a subclass of string.
