### ISSUE TITLE
Wheels for musllinux_1_1_armv7l ?

### ISSUE THREAD

**Issue by devbis** [ijl/orjson#278]
Is it possible to build and publish wheels for musl armv7?
It is a quite popular architecture for OpenWrt builds and compiling it on tiny routers is almost impossible.

**Comment by dynasticorpheus** [comment]
@devbis  Perhaps these wheels are useful for you too? Had to create to support running Home Assistant on OpenWrt:

https://github.com/dynasticorpheus/orjson/actions/runs/2609808824

**Comment by devbis** [comment]
@dynasticorpheus That's awesome! I need it for the same reason while HA switched to orjson. 
Some patching for backporting to builtin json helps, but it is bad for long-term solution.

**Comment by devbis** [comment]
@dynasticorpheus I have missing symbols after installing the wheel on openwrt. Do you have this issue?

```
# ldd orjson.cpython-39-arm-linux-gnueabihf.so
	ldd (0x76f21000)
	libgcc_s-0c8db386.so.1 => ./../orjson.libs/libgcc_s-0c8db386.so.1 (0x76e5b000)
	libc.so => ldd (0x76f21000)
Error relocating orjson.cpython-39-arm-linux-gnueabihf.so: PyTuple_New: symbol not found
Error relocating orjson.cpython-39-arm-linux-gnueabihf.so: PyModule_AddObject: symbol not found
Error relocating orjson.cpython-39-arm-linux-gnueabihf.so: _PyLong_AsByteArray: symbol not found
Error relocating orjson.cpython-39-arm-linux-gnueabihf.so: PyObject_VectorcallMethod: symbol not found
Error relocating orjson.cpython-39-arm-linux-gnueabihf.so: PyDict_New: symbol not found
```

**Comment by dynasticorpheus** [comment]
@devbis I was not aware but indeed have the same however the .so in below wheels also have the same so wondering if this is really an issue as everything does seem to work on my install.

https://wheels.home-assistant.io/musllinux/

**Comment by devbis** [comment]
I seen. My installation doesn't work with built wheels because *.so seems to be broken for ht reason above:
```
# python3 -m orjson
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
  File "/usr/lib/python3.9/site-packages/orjson/__init__.py", line 1, in <module>
    from .orjson import *
ModuleNotFoundError: No module named 'orjson.orjson'
```

**Comment by dynasticorpheus** [comment]
@devbis  Same for me when doing fresh install, when I rename the .so in /site-packages/orjson folder from orjson.cpython-39-arm-linux-gnueabihf.so to orjson.so it starts working
