### ISSUE TITLE
aws-sam-cli arm64 build fails because of orjson

### ISSUE THREAD

**Issue by davidfilat** [ijl/orjson#280]
I'm trying to migrate our stack to use Graviton ARM64 processors for all python lambdas and also to make the builds faster on the M1 Macbooks we use for development. But the `sam build` command fails and after investigating the issue it seems the problem is caused by `orjson` or one of it's dependencies, as it requires rust to be installed. If I remove `orjson` from `pyproject.toml` or `requirements.txt` the build succeeds.

Here is the output I get:

```
$ poetry export --without-hashes --with-credentials -o requirements.txt
$ SAM_CLI_TELEMETRY=0 sam build -m requirements.txt -t template.yaml --debug --use-container

2022-07-14 17:56:08,405 | Using config file: samconfig.toml, config environment: default
2022-07-14 17:56:08,405 | Expand command line arguments to:
2022-07-14 17:56:08,405 | --template_file=/Users/davidfilat/dunelm/customer-profile-api/template.yaml --manifest=requirements.txt --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-07-14 17:56:08,655 | 'build' command is called
2022-07-14 17:56:08,655 | Starting Build inside a container
2022-07-14 17:56:08,662 | Collected default values for parameters: {'CertificateArn': '/ACM/CertificateArn/dunelm.io', 'VPCSecurityGroupIDs': '/VpcConfig/SecurityGroupIds', 'VPCSubnetIDs': '/VpcConfig/SubnetIds', 'CustomerDBName': '/CustomerProfileAPI/CustomerDBName', 'SnowflakeDataWarehouseDB': '/Snowflake/DataWarehouseDB', 'SnowflakeCDPWarehouse': '/Snowflake/Warehouse/CDP'}
2022-07-14 17:56:08,671 | There is no customer defined id or cdk path defined for resource DomainName, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,671 | There is no customer defined id or cdk path defined for resource BasePathMapping, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,671 | There is no customer defined id or cdk path defined for resource OfflineCustomerOrdersLambda, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,671 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,672 | 0 stacks found in the template
2022-07-14 17:56:08,672 | Collected default values for parameters: {'CertificateArn': '/ACM/CertificateArn/dunelm.io', 'VPCSecurityGroupIDs': '/VpcConfig/SecurityGroupIds', 'VPCSubnetIDs': '/VpcConfig/SubnetIds', 'CustomerDBName': '/CustomerProfileAPI/CustomerDBName', 'SnowflakeDataWarehouseDB': '/Snowflake/DataWarehouseDB', 'SnowflakeCDPWarehouse': '/Snowflake/Warehouse/CDP'}
2022-07-14 17:56:08,678 | There is no customer defined id or cdk path defined for resource DomainName, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,678 | There is no customer defined id or cdk path defined for resource BasePathMapping, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,678 | There is no customer defined id or cdk path defined for resource OfflineCustomerOrdersLambda, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,678 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-07-14 17:56:08,678 | 4 resources found in the stack 
2022-07-14 17:56:08,678 | Found Serverless function with name='OfflineCustomerOrdersLambda' and CodeUri='customerProfileApi'
2022-07-14 17:56:08,678 | --base-dir is not presented, adjusting uri customerProfileApi relative to /Users/davidfilat/dunelm/customer-profile-api/template.yaml
2022-07-14 17:56:08,686 | Your template contains a resource with logical ID "ServerlessRestApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
2022-07-14 17:56:08,686 | Instantiating build definitions
2022-07-14 17:56:08,688 | Same function build definition found, adding function (Previous: BuildDefinition(python3.9, /Users/davidfilat/dunelm/customer-profile-api/customerProfileApi, Zip, , 85285d67-9c6f-4ce3-9166-e702f96c48da, {}, {}, arm64, []), Current: BuildDefinition(python3.9, /Users/davidfilat/dunelm/customer-profile-api/customerProfileApi, Zip, , 10173972-c7ea-4c6c-9a3b-09eff61d97ec, {}, {}, arm64, []), Function: Function(function_id='OfflineCustomerOrdersLambda', name='OfflineCustomerOrdersLambda', functionname='OfflineCustomerOrdersLambda', runtime='python3.9', memory=256, timeout=30, handler='offline_orders.get_offline_orders.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/davidfilat/dunelm/customer-profile-api/customerProfileApi', environment={'Variables': {'CUSTOMER_DB_CRED_SECRET_ARN': 'CustomerDBConnectionSecretArn', 'CUSTOMER_DATABASE_NAME': '/CustomerProfileAPI/CustomerDBName', 'SNOWFLAKE_CRED_ARN': 'SnowflakeCDPSecretArn', 'SNOWFLAKE_WAREHOUSE': '/Snowflake/Warehouse/CDP', 'DATA_WAREHOUSE_TABLE': '/Snowflake/DataWarehouseDB', 'IS_SAM_LOCAL': True}}, rolearn=None, layers=[], events={'ValidateResource': {'Type': 'Api', 'Properties': {'Path': '/api/v1/offline-customer-orders', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'OfflineCustomerOrdersLambda'}, inlinecode=None, codesign_config_arn=None, architectures=['arm64'], function_url_config=None, stack_path=''))
2022-07-14 17:56:08,689 | Building codeuri: /Users/davidfilat/dunelm/customer-profile-api/customerProfileApi runtime: python3.9 metadata: {} architecture: arm64 functions: OfflineCustomerOrdersLambda
2022-07-14 17:56:08,689 | Building to following folder /Users/davidfilat/dunelm/customer-profile-api/.aws-sam/build/OfflineCustomerOrdersLambda

Fetching public.ecr.aws/sam/build-python3.9:latest-arm64 Docker container image......
2022-07-14 17:56:11,099 | Mounting /Users/davidfilat/dunelm/customer-profile-api/customerProfileApi as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/manifest/requirements.txt --dest /tmp/samcli/scratch --exists-action i
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 51, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 156, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 258, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(scratch_directory, requirements_filepath)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 282, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 365, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 718, in download_all_dependencies
    raise PackageDownloadError(error)
aws_lambda_builders.workflows.python_pip.packager.PackageDownloadError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflow.py", line 301, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 57, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.

Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 51, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 156, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 258, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(scratch_directory, requirements_filepath)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 282, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 365, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 718, in download_all_dependencies
    raise PackageDownloadError(error)
aws_lambda_builders.workflows.python_pip.packager.PackageDownloadError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflow.py", line 301, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 57, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/__main__.py", line 118, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/builder.py", line 164, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflow.py", line 95, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.9/site-packages/aws_lambda_builders/workflow.py", line 308, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.

2022-07-14 17:56:33,860 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.\nPlease see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.\nTo avoid this problem you can invoke Python with '-m pip' instead of running pip directly.\n  error: subprocess-exited-with-error\n  \n  \u00d7 Preparing metadata (pyproject.toml) did not run successfully.\n  \u2502 exit code: 1\n  \u2570\u2500> [6 lines of output]\n      \n      Cargo, the Rust package manager, is not installed or is not on PATH.\n      This package requires Rust and Cargo to compile extensions. Install it through\n      the system's package manager or via https://rustup.rs/\n      \n      Checking for Rust toolchain....\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\nerror: metadata-generation-failed\n\n\u00d7 Encountered error while generating package metadata.\n\u2570\u2500> See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\nWARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.\nYou should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.\n"}}
Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.9 -m pip install --upgrade pip' command.

make: [build] Error 1 (ignored)
```

Here are the contents of my `pyproject.toml`:
```toml
[tool.poetry]
name = "customerProfileApi"
version = "0.0.1"
description = ""

[[tool.poetry.source]]
name = "gitlab_common_data_lib"
url = "https://gitlab.com/api/v4/projects/***/packages/pypi/simple"

[tool.poetry.dependencies]
python = ">=3.8,<3.9"
aws-xray-sdk = "^2.10.0"
orjson = "^3.6.0"
snowflake-sqlalchemy = "^1.3.4"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
bandit = "^1.7.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
pytest-mock = "^3.8.2"
pytest-sugar = "^0.9.5"
flake8 = "^4.0.1"
black = "^22.6.0"
safety = "^2.0.0"
cfn-lint = "^0.56.2"
isort = "^5.10.0"
types-orjson = "^3.6.2"
types-boto = "^2.49.16"
mypy = "^0.961"
python-dotenv = "^0.20.0"

disallow_untyped_defs = "True"
```

**Comment by davidfilat** [comment]
Why was the is issue closed? @ijl

**Comment by davidfilat** [comment]
@ijl I suppose the wheels weren't published for the latest version, because if I downgrade to v. 3.7.1 everything works fine.
