### ISSUE TITLE
Failed to generate cffi declarations using python3: exit status: 1

### ISSUE THREAD

**Issue by anoduck** [ijl/orjson#328]
Orjson is a dependency for my projects I have tried to install through the years, and I have always run up on difficulty installing it. Thankfully, my knowledge base has increased, and I was much more successful than previous attempts. 

Maturin is successfully installed, python version is 3.10.8. It appears to have successfully completed all the rust compilations, but failed during parsing C.

```bash
   Compiling arrayvec v0.7.2
   Compiling compact_str v0.6.1
   Compiling beef v0.5.2
   Compiling bytecount v0.6.3
   Compiling simdutf8 v0.1.4
   Compiling associative-cache v1.0.1
   Compiling smallvec v1.10.0
    Finished release [optimized] target(s) in 37.36s
💥 maturin failed
  Caused by: Failed to generate cffi declarations using python3: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 336, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/usr/local/lib/python3.10/site-packages/pycparser/c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.10/site-packages/pycparser/c_parser.py", line 1845, in p_error
    self._parse_error(
  File "/usr/local/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:63:31: before: *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 389, in parse
    self._internal_parse(csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 394, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 338, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 367, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "int orjson_init_exec(PyObject *mptr);"
<cdef source string>:63:31: before: *
```

Getting hung on 63:31 of some file.

**Comment by anoduck** [comment]
Per #191, due to facilitation of cffi, Orjson does not support musl/unix/bsd/haiku. In other words, any operating system that does not incorporate gnu libc is incompatible.

**Comment by anoduck** [comment]
Well, I do believe my earlier discovery might have been incorrect. 

My os, OpenBSD, does provide a maturin package in the distribution repository and therefore does support building packages with it. Although, I am sure the compatibility is dependent on what bindings maturin uses. Rust is also fully supported. Also, python cffi is completely compatible as well, and used as a dependency for many other packages. So, it appears the difficulties and errors are specific to Orjson, and originated from Orjson.

Below is output from compilation with the distribution's maturin package:

```bash

Using CPython 3.10 at python3 to generate the cffi bindings
📦 Including files matching "build.rs"
📦 Including files matching "Cargo.lock"
📦 Including files matching "include/**/*"
📦 Built source distribution to /home/user/orjson/target/wheels/orjson-3.8.3.tar.gz
   Compiling orjson v3.8.3 (/home/user/orjson)
    Finished release [optimized] target(s) in 18.79s
💥 maturin failed
  Caused by: Failed to generate cffi declarations using python3: exit status: 1
--- Stdout:

--- Stderr:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 336, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/usr/local/lib/python3.10/site-packages/pycparser/c_parser.py", line 147, in parse
    return self.cparser.parse(
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/local/lib/python3.10/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/local/lib/python3.10/site-packages/pycparser/c_parser.py", line 1931, in p_error
    self._parse_error(
  File "/usr/local/lib/python3.10/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:63:31: before: *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 389, in parse
    self._internal_parse(csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 394, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 338, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/local/lib/python3.10/site-packages/cffi/cparser.py", line 367, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "int orjson_init_exec(PyObject *mptr);"
<cdef source string>:63:31: before: *

```
