### ISSUE TITLE
3.8.9 segfaults with Python 3.12.0a7

### ISSUE THREAD

**Issue by Gelbpunkt** [ijl/orjson#372]
Hi there! I'm using orjson 3.8.9  built from source on Alpine Linux Edge with Python 3.12.0a7 @ around https://github.com/python/cpython/commit/b4978ff872be5102117b4e25d93dbbb4e04c8292.

There is a pretty simple repro that consistently segfaults for me:
```py
Python 3.12.0a7+ (main, Apr  5 2023, 22:04:14) [GCC 12.2.1 20220924] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import orjson
>>> orjson.loads('{"id": "440873286537183232", "username": "IdleRPG Beta", "global_name": null, "display_name": null, "avatar": "96c82adf2a0f3c063e06fb2a820739ae", "avatar_decoration": null, "discriminator": "2780", "public_flags": 0, "flags": 0, "bot": true, "banner": null, "banner_color": null, "accent_color": null, "bio": "", "locale": "en-US", "mfa_enabled": true, "premium_type": 0, "linked_users": [], "email": null, "verified": true}')

Program received signal SIGSEGV, Segmentation fault.
```

I've ran this through gdb to get some info and it gives me `0x00007ffff795145f in pymalloc_alloc (_unused_ctx=0x0, nbytes=53) at Objects/obmalloc.c:1308` as the segfault location ([link to the line](https://github.com/python/cpython/blob/main/Objects/obmalloc.c#L1308)).

If it helps, I have published a Docker image of the python build so you should be able to reproduce it in a container based on `docker.io/gelbpunkt/python:latest`.

**Comment by Gelbpunkt** [comment]
Here's some more info: `{"a": "b"}` does not repro this, but `{"a": 5}` does (that's a much simpler repro).
Full backtrace from gdb:
```
#0  0x00007ffff7982141 in pymalloc_alloc (_unused_ctx=0x0, nbytes=48) at Objects/obmalloc.c:1308
#1  _PyObject_Calloc (elsize=48, nelem=1, ctx=0x0) at Objects/obmalloc.c:1346
#2  PyMem_Calloc (elsize=48, nelem=1) at Objects/obmalloc.c:600
#3  _resize_tokens_array (p=0x7ffff6cd1750) at Parser/pegen.c:186
#4  _PyPegen_fill_token (p=0x7ffff6cd1750) at Parser/pegen.c:236
#5  0x00007ffff798a278 in _PyPegen_expect_token (type=1, p=p@entry=0x7ffff6cd1750) at Parser/pegen.c:355
#6  _PyPegen_name_token (p=p@entry=0x7ffff6cd1750) at Parser/pegen.c:520
#7  0x00007ffff798c337 in t_primary_raw (p=p@entry=0x7ffff6cd1750) at Parser/parser.c:18012
#8  0x00007ffff798a471 in t_primary_rule (p=0x7ffff6cd1750) at Parser/parser.c:17962
#9  single_subscript_attribute_target_rule (p=p@entry=0x7ffff6cd1750) at Parser/parser.c:17852
#10 0x00007ffff7987532 in _tmp_12_rule (p=0x7ffff6cd1750) at Parser/parser.c:24501
#11 assignment_rule (p=0x7ffff6cd1750) at Parser/parser.c:2254
#12 simple_stmt_rule (p=p@entry=0x7ffff6cd1750) at Parser/parser.c:1661
#13 0x00007ffff7986f33 in simple_stmts_rule (p=p@entry=0x7ffff6cd1750) at Parser/parser.c:1555
#14 0x00007ffff7a61ff9 in statement_newline_rule (p=0x7ffff6cd1750) at Parser/parser.c:1458
#15 interactive_rule (p=0x7ffff6cd1750) at Parser/parser.c:1116
#16 _PyPegen_parse (p=p@entry=0x7ffff6cd1750) at Parser/parser.c:39036
#17 0x00007ffff7a61acc in _PyPegen_run_parser (p=p@entry=0x7ffff6cd1750) at Parser/pegen.c:825
#18 0x00007ffff7aa33e9 in _PyPegen_run_parser_from_file_pointer (arena=0x7ffff7e79750, errcode=0x7fffffffea04, flags=0x7fffffffeb28, ps2=<optimized out>, ps1=0x7ffff77182f8 ">>> ",
    enc=0x7ffff769dd38 "utf-8", filename_ob=0x7ffff7a61acc <_PyPegen_run_parser+12>, start_rule=256, fp=0x7ffff769dd38) at Parser/pegen.c:897
#19 _PyParser_ASTFromFile (fp=fp@entry=0x7ffff7ffb1c0, filename_ob=filename_ob@entry=0x7ffff7718240, enc=enc@entry=0x7ffff769dd38 "utf-8", mode=mode@entry=256,
    ps1=ps1@entry=0x7ffff77182f8 ">>> ", ps2=<optimized out>, flags=0x7fffffffeb28, errcode=0x7fffffffea04, arena=0x7ffff7e79750) at Parser/peg_api.c:26
#20 0x00007ffff793eb48 in PyRun_InteractiveOneObjectEx (fp=fp@entry=0x7ffff7ffb1c0, filename=filename@entry=0x7ffff7718240, flags=flags@entry=0x7fffffffeb28) at Python/pythonrun.c:240
#21 0x00007ffff793ed96 in _PyRun_InteractiveLoopObject (fp=0x7ffff7ffb1c0, filename=0x7ffff7718240, flags=0x7fffffffeb28) at Python/pythonrun.c:137
#22 0x00007ffff7aa1a97 in _PyRun_AnyFileObject (fp=0x7ffff7ffb1c0, filename=0x7ffff7718240, closeit=0, flags=0x7fffffffeb28) at Python/pythonrun.c:72
#23 0x00007ffff793eeba in PyRun_AnyFileExFlags (fp=0x7ffff7ffb1c0, filename=<optimized out>, closeit=0, flags=0x7fffffffeb28) at Python/pythonrun.c:104
#24 0x00007ffff7a9a892 in pymain_run_stdin (config=0x7ffff7dbdba0 <_PyRuntime+338912>) at Modules/main.c:520
#25 pymain_run_python (exitcode=0x7fffffffeb24) at Modules/main.c:613
#26 Py_RunMain () at Modules/main.c:689
#27 0x00007ffff7a48b07 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:743
#28 0x00007ffff7f809ca in ?? () from /lib/ld-musl-x86_64.so.1
#29 0x00007ffff7f809a2 in ?? () from /lib/ld-musl-x86_64.so.1
#30 0x00007fffffffeca0 in ?? ()
#31 0x0000000000000000 in ?? ()
```

**Comment by Gelbpunkt** [comment]
Thanks for the quick fix!
