### ISSUE TITLE
Cannot build cp37 linux armv7l (Raspberry Pi)

### ISSUE THREAD

**Issue by tcirstea** [ijl/orjson#38]
There's no wheel for the raspberry pi, and I cannot seem to build it.
The dependencies (maturin mainly) have been built and installed.
I have rust beta (since there doesn't seem to be a nightly published for this platform).

Output from pip3 wheel:
```
  Successfully installed maturin-0.7.6 toml-0.10.0
  Cleaning up...
  Cleaned build tracker '/tmp/pip-req-tracker-wbgzc9qi'
done
  Running setup.py (path:/tmp/pip-wheel-a9ak7sy7/orjson/setup.py) egg_info for package orjson
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-a9ak7sy7/orjson/setup.py'
Cleaning up...
  Removing source in /tmp/pip-wheel-a9ak7sy7/orjson
Removed orjson from https://files.pythonhosted.org/packages/d0/e2/5042aa4907face747f7d68fa694a5781c07f9263bbaebfeba42a542f1ec3/orjson-2.1.2.tar.gz#sha256=40a6b0c17d94907d5c26ed2225fc465e48aa0eac8fd5d46d01beb105e4db06c1 from build tracker '/tmp/pip-req-tracker-wbgzc9qi'
Removed build tracker '/tmp/pip-req-tracker-wbgzc9qi'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-a9ak7sy7/orjson/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/wheel.py", line 161, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 473, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 723, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-a9ak7sy7/orjson/
```

**Comment by tcirstea** [comment]
Downloaded the source straight from PyPi, and it is indeed missing the `setup.py` file. 

However, upon pulling the repo, I still can't build because the build script conflicts with pip/setup.py
```
Processing ./orjson
  Installing build dependencies ... done
Building wheels for collected packages: orjson
  Running setup.py bdist_wheel for orjson ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ewds1m79/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-l8t0xtg4:
  running bdist_wheel
  running build
  installing to build/bdist.linux-armv7l/wheel
  running install
  running install_egg_info
  running egg_info
  creating orjson.egg-info
  writing orjson.egg-info/PKG-INFO
  writing dependency_links to orjson.egg-info/dependency_links.txt
  writing top-level names to orjson.egg-info/top_level.txt
  writing manifest file 'orjson.egg-info/SOURCES.txt'
  reading manifest file 'orjson.egg-info/SOURCES.txt'
  writing manifest file 'orjson.egg-info/SOURCES.txt'
  error: [Errno 20] Not a directory: 'build/bdist.linux-armv7l'
```
I'll leave this issue open since it requires fixing, but I'm unblocked.

**Comment by tcirstea** [comment]
Turns out `maturin` doesn't support ARM...

**Comment by ijl** [comment]
If PyPI supports ARM (I have just looked a little and seen it's a mess), CI supports ARM (same), I would not mind trying to support it. For now it's ununsupported.
