### ISSUE TITLE
Add support for missing numpy int/float types

### ISSUE THREAD

**Issue by randomir** [ijl/orjson#469]
`orjson` seems to support all basic integer and real numeric [numpy types](https://numpy.org/doc/stable/user/basics.types.html), except:
[`longlong`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.longlong), [`ulonglong`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.ulonglong), and [`longdouble`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.longdouble) (aka [`float128`](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.float128), if platform-supported).

```python
>>> import numpy
>>> import orjson
>>> 
>>> orjson.dumps(numpy.longlong(1), option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.longlong
>>> orjson.dumps(numpy.ulonglong(1), option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.ulonglong
>>> orjson.dumps(numpy.longdouble(1.0), option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.longdouble
>>> orjson.dumps(numpy.float128(1.0), option=orjson.OPT_SERIALIZE_NUMPY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Type is not JSON serializable: numpy.longdouble
```

It would be nice to have the full coverage of numpy numeric scalar types.

**Comment by randomir** [comment]
Oh, looks like serialization of `numpy.intc` and `numpy.uintc` is also [not working on Windows](https://app.circleci.com/pipelines/github/dwavesystems/dwave-inspector/298/workflows/b5c5f1fd-d2bb-44ad-a094-8a6ffcc588b2/jobs/6438).

**Comment by randomir** [comment]
Possible to get some comment from a human, before dismissing and closing as stale?
