### ISSUE TITLE
install on pypy3

### ISSUE THREAD

**Issue by includeamin** [ijl/orjson#72]
Hi,
i have problem with installing orjson on pypy3

``` sh
pypy3 -m pip install orjson
```
## output
```
Collecting orjson
  Using cached https://files.pythonhosted.org/packages/8e/7c/e9a6f52e344c480be42fddeb1a0593283ecc1c06293ef210af4521a5b6f5/orjson-2.6.3.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/pypy3 /usr/local/Cellar/pypy3/7.3.0/libexec/site-packages/pip-19.3.1-py3.6.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/f2/55729nz54_n67nbl49d2dq8w0000gn/T/tmpw2i829mz
         cwd: /private/var/folders/f2/55729nz54_n67nbl49d2dq8w0000gn/T/pip-install-zed0ae6r/orjson
    Complete output (20 lines):
    Checking for Rust toolchain....
    Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/f2/55729nz54_n67nbl49d2dq8w0000gn/T/pip-modern-metadata-lzf3wd4s --manylinux=off --rustc-extra-args=-Zmutable-noalias -C target-feature=+sse2 --strip=on`
    Traceback (most recent call last):
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/site-packages/pip-19.3.1-py3.6.egg/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/site-packages/pip-19.3.1-py3.6.egg/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/site-packages/pip-19.3.1-py3.6.egg/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/f2/55729nz54_n67nbl49d2dq8w0000gn/T/pip-build-env-wk0qwdr9/overlay/site-packages/maturin/__init__.py", line 133, in prepare_metadata_for_build_wheel
        output = subprocess.check_output(command)
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/subprocess.py", line 744, in __init__
        restore_signals, start_new_session)
      File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/subprocess.py", line 1392, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'maturin': 'maturin'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/pypy3 /usr/local/Cellar/pypy3/7.3.0/libexec/site-packages/pip-19.3.1-py3.6.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/f2/55729nz54_n67nbl49d2dq8w0000gn/T/tmpw2i829mz Check the logs for full command output.


```

**Comment by ijl** [comment]
It doesn't support PyPy. If someone wants to handle the differences in `datetime` implementations and add `cfg` for the CPython-specific APIs, it would, and I'd accept a patch.
